#name of the properties file

name=LoggerConfigFile

#Declaring logger for business logic
logger.file.name=com.ftr.vehicle.utility
logger.file.level=DEBUG
logger.file.appenderRef.file.ref=LoggerAppender
logger.file.additivity=false

#declaring logger for business console
logger.console.name=com.ftr.vehicle
logger.console.level=DEBUG
logger.console.appenderRef.file.ref=ConsoleAppender
logger.console.additivity=false

#file appender
appender.file.name=LoggerAppender
appender.file.type=File
appender.file.fileName=log/Error.log

#Logging Patter
appender.file.layout.type=PatternLayout
appender.file.layout.pattern=%d{dd-MMM-yyyy HH:mm:ss} %level -%m%n

#console appender
appender.console.name=ConsoleAppender
appender.console.type=Console

#logging pattern for console
appender.console.layout.type=PatternLayout
appender.console.layout.patter=%m%n